import fs from 'fs';

// Read the pokemon data file
const filePath = './src/data/pokemonData.ts';
let content = fs.readFileSync(filePath, 'utf8');

// Pokemon Japanese name to English name mapping (based on pokemon_list_enName.md)
const pokemonEnNameMap = {
  'フシギダネ': 'Bulbasaur',
  'フシギソウ': 'Ivysaur',
  'フシギバナ': 'Venusaur',
  'ヒトカゲ': 'Charmander',
  'リザード': 'Charmeleon',
  'リザードン': 'Charizard',
  'ゼニガメ': 'Squirtle',
  'カメール': 'Wartortle',
  'カメックス': 'Blastoise',
  'キャタピー': 'Caterpie',
  'トランセル': 'Metapod',
  'バタフリー': 'Butterfree',
  'コラッタ': 'Rattata',
  'ラッタ': 'Raticate',
  'アーボ': 'Ekans',
  'アーボック': 'Arbok',
  'ピカチュウ': 'Pikachu',
  'ピカチュウ(ハロウィン)': 'Pikachu',
  'ピカチュウ(ホリデー)': 'Pikachu',
  'ライチュウ': 'Raichu',
  'ピッピ': 'Clefairy',
  'ピクシー': 'Clefable',
  'ロコン': 'Vulpix',
  'キュウコン': 'Ninetales',
  'ロコン(アローラのすがた)': 'Vulpix',
  'キュウコン(アローラのすがた)': 'Ninetales',
  'プリン': 'Jigglypuff',
  'プクリン': 'Wigglytuff',
  'ディグダ': 'Diglett',
  'ダグトリオ': 'Dugtrio',
  'ニャース': 'Meowth',
  'ペルシアン': 'Persian',
  'コダック': 'Psyduck',
  'ゴルダック': 'Golduck',
  'マンキー': 'Mankey',
  'オコリザル': 'Primeape',
  'ガーディ': 'Growlithe',
  'ウインディ': 'Arcanine',
  'マダツボミ': 'Bellsprout',
  'ウツドン': 'Weepinbell',
  'ウツボット': 'Victreebel',
  'イシツブテ': 'Geodude',
  'ゴローン': 'Graveler',
  'ゴローニャ': 'Golem',
  'ヤドン': 'Slowpoke',
  'ヤドラン': 'Slowbro',
  'コイル': 'Magnemite',
  'レアコイル': 'Magneton',
  'カモネギ': "Farfetch'd",
  'ドードー': 'Doduo',
  'ドードリオ': 'Dodrio',
  'ゴース': 'Gastly',
  'ゴースト': 'Haunter',
  'ゲンガー': 'Gengar',
  'イワーク': 'Onix',
  'カラカラ': 'Cubone',
  'ガラガラ': 'Marowak',
  'ラッキー': 'Chansey',
  'ガルーラ': 'Kangaskhan',
  'バリヤード': 'Mr. Mime',
  'カイロス': 'Pinsir',
  'メタモン': 'Ditto',
  'イーブイ': 'Eevee',
  'イーブイ(ホリデー)': 'Eevee',
  'シャワーズ': 'Vaporeon',
  'サンダース': 'Jolteon',
  'ブースター': 'Flareon',
  'ミニリュウ': 'Dratini',
  'ハクリュー': 'Dragonair',
  'カイリュー': 'Dragonite',
  'チコリータ': 'Chikorita',
  'ベイリーフ': 'Bayleef',
  'メガニウム': 'Meganium',
  'ヒノアラシ': 'Cyndaquil',
  'マグマラシ': 'Quilava',
  'バクフーン': 'Typhlosion',
  'ワニノコ': 'Totodile',
  'アリゲイツ': 'Croconaw',
  'オーダイル': 'Feraligatr',
  'ピチュー': 'Pichu',
  'ピィ': 'Cleffa',
  'ププリン': 'Igglybuff',
  'トゲピー': 'Togepi',
  'トゲチック': 'Togetic',
  'ネイティ': 'Natu',
  'ネイティオ': 'Xatu',
  'メリープ': 'Mareep',
  'モココ': 'Flaaffy',
  'デンリュウ': 'Ampharos',
  'ウソッキー': 'Sudowoodo',
  'ウパー': 'Wooper',
  'ウパー(パルデアのすがた)': 'Wooper',
  'ヌオー': 'Quagsire',
  'エーフィ': 'Espeon',
  'ブラッキー': 'Umbreon',
  'ヤミカラス': 'Murkrow',
  'ヤドキング': 'Slowking',
  'ソーナンス': 'Wobbuffet',
  'ハガネール': 'Steelix',
  'ヘラクロス': 'Heracross',
  'ニューラ': 'Sneasel',
  'デリバード': 'Delibird',
  'デルビル': 'Houndour',
  'ヘルガー': 'Houndoom',
  'ハピナス': 'Blissey',
  'ライコウ': 'Raikou',
  'エンテイ': 'Entei',
  'スイクン': 'Suicune',
  'ヨーギラス': 'Larvitar',
  'サナギラス': 'Pupitar',
  'バンギラス': 'Tyranitar',
  'キモリ': 'Treecko',
  'ジュプトル': 'Grovyle',
  'ジュカイン': 'Sceptile',
  'アチャモ': 'Torchic',
  'ワカシャモ': 'Combusken',
  'バシャーモ': 'Blaziken',
  'ミズゴロウ': 'Mudkip',
  'ヌマクロー': 'Marshtomp',
  'ラグラージ': 'Swampert',
  'ラルトス': 'Ralts',
  'キルリア': 'Kirlia',
  'サーナイト': 'Gardevoir',
  'ナマケロ': 'Slakoth',
  'ヤルキモノ': 'Vigoroth',
  'ケッキング': 'Slaking',
  'ヤミラミ': 'Sableye',
  'クチート': 'Mawile',
  'ココドラ': 'Aron',
  'コドラ': 'Lairon',
  'ボスゴドラ': 'Aggron',
  'プラスル': 'Plusle',
  'マイナン': 'Minun',
  'ゴクリン': 'Gulpin',
  'マルノーム': 'Swalot',
  'チルット': 'Swablu',
  'チルタリス': 'Altaria',
  'カゲボウズ': 'Shuppet',
  'ジュペッタ': 'Banette',
  'アブソル': 'Absol',
  'ソーナノ': 'Wynaut',
  'タマザラシ': 'Spheal',
  'トドグラー': 'Sealeo',
  'トドゼルガ': 'Walrein',
  'コリンク': 'Shinx',
  'ルクシオ': 'Luxio',
  'レントラー': 'Luxray',
  'フワンテ': 'Drifloon',
  'フワライド': 'Drifblim',
  'ドンカラス': 'Honchkrow',
  'ウソハチ': 'Bonsly',
  'マネネ': 'Mime Jr.',
  'ピンプク': 'Happiny',
  'リオル': 'Riolu',
  'ルカリオ': 'Lucario',
  'グレッグル': 'Croagunk',
  'ドクロッグ': 'Toxicroak',
  'ユキカブリ': 'Snover',
  'ユキノオー': 'Abomasnow',
  'マニューラ': 'Weavile',
  'ジバコイル': 'Magnezone',
  'トゲキッス': 'Togekiss',
  'リーフィア': 'Leafeon',
  'グレイシア': 'Glaceon',
  'エルレイド': 'Gallade',
  'クレセリア': 'Cresselia',
  'ダークライ': 'Darkrai',
  'ムンナ': 'Munna',
  'ムシャーナ': 'Musharna',
  'ワシボン': 'Rufflet',
  'ウォーグル': 'Braviary',
  'ニンフィア': 'Sylveon',
  'デデンネ': 'Dedenne',
  'アゴジムシ': 'Grubbin',
  'デンヂムシ': 'Charjabug',
  'クワガノン': 'Vikavolt',
  'ヌイコグマ': 'Stufful',
  'キテルグマ': 'Bewear',
  'キュワワー': 'Comfey',
  'ミミッキュ': 'Mimikyu',
  'ウッウ': 'Cramorant',
  'エレズン': 'Toxel',
  'ストリンダー(ハイなすがた)': 'Toxtricity',
  'ストリンダー(ローなすがた)': 'Toxtricity',
  'ニャオハ': 'Sprigatito',
  'ニャローテ': 'Floragato',
  'マスカーニャ': 'Meowscarada',
  'ホゲータ': 'Fuecoco',
  'アチゲータ': 'Crocalor',
  'ラウドボーン': 'Skeledirge',
  'クワッス': 'Quaxly',
  'ウェルカモ': 'Quaxwell',
  'ウェーニバル': 'Quaquaval',
  'パモ': 'Pawmi',
  'パモット': 'Pawmo',
  'パーモット': 'Pawmot',
  'ドオー': 'Clodsire'
};

// Add enName field after displayName for each pokemon
Object.keys(pokemonEnNameMap).forEach(pokemonName => {
  const enName = pokemonEnNameMap[pokemonName];
  // Match pattern: displayName: "pokemonName", followed by name:
  // Replace with displayName, enName, name
  const pattern = new RegExp(`(displayName: "${pokemonName}",\\s*\\n)(\\s*)(name:)`, 'g');
  content = content.replace(pattern, `$1$2enName: "${enName}",\n$2$3`);
});

fs.writeFileSync(filePath, content, 'utf8');
console.log('Pokemon English names added successfully!');
